title: Kotachi Liu # your name (or website title) here
logo: "/images/surf.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Student in Ocean Engineering at the University of Rhode Island
  <br><br>
  [URI Department of Ocean Engineering](https://web.uri.edu/engineering/about/ocean-engineering/)
  <br><br>
  [URI Graduate School of Oceanography](https://web.uri.edu/gso/)
  <br><br>
  [Smart Ocean Systems Laboratory](https://soslab.wordpress.com/)
  <br><br>
  [Roman Laboratory](http://www.gso.uri.edu/cnr/www/)
  <br><br>
  <a href="https://www.linkedin.com/in/kotachiliu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
